### ISSUE TITLE
Set up the Database

### ISSUE THREAD

**Issue by martapolii** [martapolii/RAVENCLAW#22]
Create a MongoDB database for the application

● Define the following collections:

- [x] users: to store user profiles and authentication data

- [x] trivia questions: to store the trivia questions and answers

- [ ]  May consider additional databases upon discussion

**Comment by hollyek02** [comment]
Database setup completed with MongoDB Atlas. Backend connected successfully. Remaining task: Whitelist team members IPs for access.
